# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  SA:
    has_velocity_limits: false #true
    max_velocity: 1.3962634016
    has_acceleration_limits: false
    max_acceleration: 0
  SE:
    has_velocity_limits: false #true
    max_velocity: 1.1344640138
    has_acceleration_limits: false
    max_acceleration: 0
  WP:
    has_velocity_limits: false #true
    max_velocity: 1.74532925199
    has_acceleration_limits: false
    max_acceleration: 0
  WR:
    has_velocity_limits: false #true
    max_velocity: 3.49065850399
    has_acceleration_limits: false
    max_acceleration: 0
  WY:
    has_velocity_limits: false #true
    max_velocity: 2.00712863979
    has_acceleration_limits: false
    max_acceleration: 0
  linkage_tr:
    has_velocity_limits: false #true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
